#%RAML 1.0 DataType
properties:
  userName:
    type: string
    minLength: 3
    maxLength: 20
    required: true
    example: "TestUser"
  password:
    type: string
    minLength: 3
    maxLength: 20
    required: true
    example: "Pass#123"